[project]
name = "spark-delta-iceberg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "jupyterlab>=4.4.1",
    "pyiceberg>=0.9.0",
    "pyspark==3.5.3",
]
